/* eslint-disable import/no-anonymous-default-export */

export default {
        0: {name: "Bernardo", children: [8], alive: true, murderer: false},
        1: {name: "Clara", children: [8], alive: true, murderer: false},
        2: {name: "Cabele", children: [9, 10], alive: true, murderer: false},
        3: {name: "Maria Eduarda", children: [9, 10], alive: true, murderer: false},
        4: {name: "Bruno", children: [11, 12], alive: true, murderer: false},
        5: {name: "Indiara", children: [11, 12], alive: true, murderer: false},
        6: {name: "Brian", children: [13], alive: true, murderer: false},
        7: {name: "Emily", children: [13], alive: true, murderer: false},
        8: {name: "Paulo", children: [16, 17, 18], alive: true, murderer: false},
        9: {name: "Daniela", children: [16, 17, 18], alive: true, murderer: false},
        10: {name: "Thiago", children: [19], alive: true, murderer: false},
        11: {name: "Stefania", children: [19], alive: true, murderer: false},
        12: {name: "Damaso", children: [20], alive: true, murderer: false},
        13: {name: "Blanco", children: [21, 22, 23, 24], alive: true, murderer: false},
        14: {name: "Maria", children: [21, 22, 23, 24], alive: true, murderer: false},
        15: {name: "Ateldy", children: [26, 27], alive: true, murderer: false},
        16: {name: "Amanda", children: [26, 27], alive: true, murderer: false},
        17: {name: "Natan", children: [28], alive: true, murderer: false},
        18: {name: "Adriely", children: [28], alive: true, murderer: false},
        19: {name: "Luciana", children: [], alive: true, murderer: false},
        20: {name: "Yan", children: [], alive: true, murderer: false},
        21: {name: "Karine", children: [], alive: true, murderer: false},
        22: {name: "Saleh", children: [], alive: true, murderer: false},
        23: {name: "Denys", children: [], alive: true, murderer: false},
        24: {name: "Mauricio", children: [31, 32], alive: true, murderer: false},
        25: {name: "Sofia", children: [31, 32], alive: true, murderer: false},
        26: {name: "Luiz", children: [], alive: true, murderer: false},
        27: {name: "Thais", children: [], alive: true, murderer: true},
        28: {name: "Rossicler", children: [], alive: true, murderer: false},
        29: {name: "Leonardo", children: [33], alive: true, murderer: false},
        30: {name: "Mariana", children: [3], alive: true, murderer: false},
        31: {name: "Sabanai", children: [34], alive: true, murderer: false},
        32: {name: "Thabata", children: [34], alive: true, murderer: false},
        33: {name: "Lamego", children: [35], alive: true, murderer: false},
        34: {name: "Juliana", children: [35], alive: true, murderer: false},
        35: {name: "Natália", children: [], alive: true, murderer: false},
}